language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION="<1.9"
  - DJANGO_VERSION="<1.10"
  - DJANGO_VERSION=">=1.10"
install: pip install -q "Django$DJANGO_VERSION" "django-ckeditor>=5.0"
script: python django_news/tests/runtests.py
